services:
  npm-app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ${DATA_PATH}:/data
      - ${LETSENCRYPT_PATH}:/etc/letsencrypt
    environment:
      TZ: Europe/London
    networks:
      - proxy_net

networks:
  proxy_net:
    name: proxy_net