services:
  nc_redis:
    image: redis:alpine
    restart: always
    networks:
      - nextcloud

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - ${NEXTCLOUD_PORT}:80
    depends_on:
      - nc_redis
    volumes:
      - /mnt/truenas/nextcloud:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=16G
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - REDIS_HOST=nc_redis
      - TZ=${TZ}
    networks:
      nextcloud:
        ipv4_address: 172.25.0.5

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - ${OPENWEBUI_PORT}:8080
    volumes:
      - open-webui:/app/backend/data
    environment:
      - PUID=${OPENWEBUI_UID}
      - PGID=${OPENWEBUI_GID}
      - TZ=${TZ}

  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - redisdata:/data

  paperless_webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless_ngx
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - ${PAPERLESS_PORT}:8000
    volumes:
      - /mnt/truenas/paperless/data:/usr/src/paperless/data
      - /mnt/truenas/paperless/media:/usr/src/paperless/media
      - ${VM_CONFIG_ROOT}/paperless/export:/usr/src/paperless/export
      - ${VM_CONFIG_ROOT}/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_URL: ${PAPERLESS_URL}
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: ${DB_HOST}
      PAPERLESS_DBUSER: ${DB_USER}
      PAPERLESS_DBPASS: ${DB_PASS}
      PAPERLESS_DBPORT: ${DB_PORT}
      PAPERLESS_DBNAME: ${DB_NAME}
      USERMAP_UID: ${PAPERLESS_UID}
      USERMAP_GID: ${PAPERLESS_GID}
      PAPERLESS_TIME_ZONE: ${TZ}

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower_debian
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: 0 0 9 * * *
      WATCHTOWER_NOTIFICATION_REPORT: true
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_REVIVE_STOPPED: false
      WATCHTOWER_NOTIFICATION_JSON: true
      WATCHTOWER_NOTIFICATION_URL: ${WT_NOTIF_URL}
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      TZ: ${TZ}

  sxng_redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - ${VM_CONFIG_ROOT}/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      gluetun:
        condition: service_started
      sxng_redis:
        condition: service_healthy

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - ${VM_CONFIG_ROOT}/gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${GLUETUN_PORT}:8080
    networks:
      - searxng
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER} # nordvpn
      - VPN_TYPE=openvpn # openvpn or wireguard
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${VPN_COUNTRY}
      - SERVER_CITIES=${VPN_CITY}
      - TZ=${TZ}
      - DNS_KEEP_NAMESERVER=on
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:
    driver: bridge
  nextcloud:
    driver: bridge
    ipam:
      config:
        - subnet: "172.25.0.0/16" # Used so that cron can access the service

volumes:
  open-webui:
  redisdata:
  caddy-data:
  caddy-config:
  valkey-data:
